apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: robotframework-dashboard-data
  namespace: robotframework-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard # Change this to your cluster's storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: robotframework-dashboard-logs
  namespace: robotframework-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard # Change this to your cluster's storage class
---
